import { Meal } from "../types/meals";

export const mockMeals: Meal[] = [
  {
    id: "tacos",
    title: "Tacos",
    emoji: "🌮",
    rating: 3,
    plannedCostTier: 1,
    locked: true,
    isFavorite: true,
    recipeUrl: "",
    ingredients: ["Tortillas", "Ground beef", "Cheddar"],
    difficulty: 2,
    expense: 2,
  },
  {
    id: "margherita",
    title: "Margherita Pizza",
    emoji: "🍕",
    rating: 2,
    plannedCostTier: 2,
    locked: false,
    isFavorite: false,
    recipeUrl: "",
    ingredients: ["Tomato", "Mozzarella", "Basil"],
    difficulty: 3,
    expense: 2,
  },
  {
    id: "stirfry",
    title: "Chicken Stir Fry",
    emoji: "🥦",
    rating: 4,
    plannedCostTier: 2,
    locked: true,
    isFavorite: true,
    recipeUrl: "",
    ingredients: ["Chicken", "Broccoli", "Ginger"],
    difficulty: 3,
    expense: 2,
  },
  {
    id: "burgers",
    title: "Burgers",
    emoji: "🍔",
    rating: 3,
    plannedCostTier: 2,
    locked: false,
    isFavorite: false,
    recipeUrl: "",
    ingredients: ["Ground beef", "Buns", "Cheese"],
    difficulty: 2,
    expense: 2,
  },
  {
    id: "salad",
    title: "Caesar Salad",
    emoji: "🥗",
    rating: 1,
    plannedCostTier: 2,
    locked: false,
    isFavorite: false,
    recipeUrl: "",
    ingredients: ["Romaine", "Parmesan", "Dressing"],
    difficulty: 1,
    expense: 1,
  },
  {
    id: "beeftacos",
    title: "Beef Tacos",
    emoji: "🌮",
    rating: 2,
    plannedCostTier: 2,
    locked: false,
    isFavorite: true,
    recipeUrl: "",
    ingredients: ["Tortillas", "Beef", "Salsa"],
    difficulty: 2,
    expense: 2,
  },
];
