import { Meal } from "../types/meals";

export const mockMeals: Meal[] = [
  {
    id: "mushroom-risotto",
    title: "Mushroom Risotto",
    emoji: "🍄",
    rating: 4.5,
    servedCount: 6,
    showServedCount: true,
    plannedCostTier: 3,
    locked: false,
    isFavorite: true,
    recipeUrl: "https://weeklyeats.app/recipes/mushroom-risotto",
    ingredients: ["Arborio rice", "Mushrooms", "Parmesan"],
    difficulty: 4,
    expense: 4,
  },
  {
    id: "sheet-pan-fajitas",
    title: "Sheet Pan Fajitas",
    emoji: "🌯",
    rating: 4.1,
    servedCount: 3,
    showServedCount: true,
    plannedCostTier: 2,
    locked: false,
    isFavorite: false,
    recipeUrl: "https://weeklyeats.app/recipes/sheet-pan-fajitas",
    ingredients: ["Chicken thighs", "Bell peppers", "Onion"],
    difficulty: 2,
    expense: 2,
  },
  {
    id: "coconut-curry",
    title: "Coconut Chickpea Curry",
    emoji: "🍛",
    rating: 4.8,
    servedCount: 8,
    showServedCount: true,
    plannedCostTier: 2,
    locked: false,
    isFavorite: true,
    recipeUrl: "https://weeklyeats.app/recipes/coconut-curry",
    ingredients: ["Chickpeas", "Coconut milk", "Spinach"],
    difficulty: 3,
    expense: 2,
  },
  {
    id: "lemon-herb-chicken",
    title: "Lemon Herb Chicken",
    emoji: "🍗",
    rating: 3.9,
    servedCount: 5,
    showServedCount: false,
    plannedCostTier: 2,
    locked: true,
    isFavorite: false,
    recipeUrl: "https://weeklyeats.app/recipes/lemon-herb-chicken",
    ingredients: ["Chicken breast", "Lemon", "Garlic"],
    difficulty: 3,
    expense: 3,
  },
  {
    id: "black-bean-bowls",
    title: "Black Bean Bowls",
    emoji: "🫘",
    rating: 4.2,
    servedCount: 2,
    showServedCount: false,
    plannedCostTier: 1,
    locked: false,
    isFavorite: true,
    recipeUrl: "https://weeklyeats.app/recipes/black-bean-bowls",
    ingredients: ["Black beans", "Rice", "Corn"],
    difficulty: 1,
    expense: 1,
  },
  {
    id: "salmon-teriyaki",
    title: "Teriyaki Salmon",
    emoji: "🐟",
    rating: 4.6,
    servedCount: 4,
    showServedCount: true,
    plannedCostTier: 3,
    locked: false,
    isFavorite: true,
    recipeUrl: "https://weeklyeats.app/recipes/teriyaki-salmon",
    ingredients: ["Salmon", "Soy sauce", "Ginger"],
    difficulty: 4,
    expense: 4,
  },
  {
    id: "veggie-tortellini-soup",
    title: "Veggie Tortellini Soup",
    emoji: "🥣",
    rating: 3.7,
    servedCount: 1,
    showServedCount: false,
    plannedCostTier: 2,
    locked: false,
    isFavorite: false,
    recipeUrl: "https://weeklyeats.app/recipes/veggie-tortellini-soup",
    ingredients: ["Tortellini", "Carrots", "Spinach"],
    difficulty: 2,
    expense: 2,
  },
  {
    id: "bbq-pulled-pork",
    title: "BBQ Pulled Pork",
    emoji: "🥪",
    rating: 4.3,
    servedCount: 7,
    showServedCount: true,
    plannedCostTier: 3,
    locked: false,
    isFavorite: false,
    recipeUrl: "https://weeklyeats.app/recipes/bbq-pulled-pork",
    ingredients: ["Pork shoulder", "BBQ sauce", "Buns"],
    difficulty: 3,
    expense: 3,
  },
  {
    id: "korean-bulgogi-bowls",
    title: "Korean Bulgogi Bowls",
    emoji: "🍱",
    rating: 4.9,
    servedCount: 6,
    showServedCount: true,
    plannedCostTier: 3,
    locked: true,
    isFavorite: true,
    recipeUrl: "https://weeklyeats.app/recipes/korean-bulgogi-bowls",
    ingredients: ["Beef", "Rice", "Kimchi"],
    difficulty: 4,
    expense: 4,
  },
  {
    id: "sweet-potato-tacos",
    title: "Sweet Potato Tacos",
    emoji: "🌮",
    rating: 3.5,
    servedCount: 2,
    showServedCount: false,
    plannedCostTier: 1,
    locked: false,
    isFavorite: false,
    recipeUrl: "https://weeklyeats.app/recipes/sweet-potato-tacos",
    ingredients: ["Sweet potatoes", "Tortillas", "Avocado"],
    difficulty: 2,
    expense: 1,
  },
  {
    id: "steak-night",
    title: "Cast Iron Steak",
    emoji: "🥩",
    rating: 4.4,
    servedCount: 5,
    showServedCount: false,
    plannedCostTier: 3,
    locked: true,
    isFavorite: true,
    recipeUrl: "https://weeklyeats.app/recipes/cast-iron-steak",
    ingredients: ["Ribeye", "Butter", "Rosemary"],
    difficulty: 5,
    expense: 5,
  },
  {
    id: "soba-noodle-salad",
    title: "Soba Noodle Salad",
    emoji: "🥢",
    rating: 3.8,
    servedCount: 1,
    showServedCount: false,
    plannedCostTier: 2,
    locked: false,
    isFavorite: false,
    recipeUrl: "https://weeklyeats.app/recipes/soba-noodle-salad",
    ingredients: ["Soba noodles", "Cabbage", "Sesame"],
    difficulty: 2,
    expense: 2,
  },
  {
    id: "baked-gnocchi",
    title: "Baked Gnocchi Florentine",
    emoji: "🧀",
    rating: 4.0,
    servedCount: 4,
    showServedCount: true,
    plannedCostTier: 2,
    locked: false,
    isFavorite: true,
    recipeUrl: "https://weeklyeats.app/recipes/baked-gnocchi",
    ingredients: ["Gnocchi", "Spinach", "Ricotta"],
    difficulty: 3,
    expense: 2,
  },
  {
    id: "fish-taco-bowls",
    title: "Fish Taco Bowls",
    emoji: "🐠",
    rating: 3.6,
    servedCount: 2,
    showServedCount: false,
    plannedCostTier: 2,
    locked: false,
    isFavorite: false,
    recipeUrl: "https://weeklyeats.app/recipes/fish-taco-bowls",
    ingredients: ["White fish", "Rice", "Cabbage slaw"],
    difficulty: 3,
    expense: 3,
  },
  {
    id: "butter-chicken",
    title: "Instant Pot Butter Chicken",
    emoji: "🍲",
    rating: 4.7,
    servedCount: 9,
    showServedCount: true,
    plannedCostTier: 2,
    locked: false,
    isFavorite: true,
    recipeUrl: "https://weeklyeats.app/recipes/butter-chicken",
    ingredients: ["Chicken thighs", "Tomato sauce", "Cream"],
    difficulty: 3,
    expense: 3,
  },
  {
    id: "veggie-lasagna",
    title: "Roasted Veggie Lasagna",
    emoji: "🍅",
    rating: 4.2,
    servedCount: 3,
    showServedCount: true,
    plannedCostTier: 3,
    locked: false,
    isFavorite: false,
    recipeUrl: "https://weeklyeats.app/recipes/veggie-lasagna",
    ingredients: ["Lasagna noodles", "Zucchini", "Ricotta"],
    difficulty: 4,
    expense: 3,
  },
  {
    id: "spicy-ramen",
    title: "Spicy Miso Ramen",
    emoji: "🍜",
    rating: 4.5,
    servedCount: 5,
    showServedCount: true,
    plannedCostTier: 2,
    locked: false,
    isFavorite: true,
    recipeUrl: "https://weeklyeats.app/recipes/spicy-ramen",
    ingredients: ["Ramen noodles", "Miso", "Soft egg"],
    difficulty: 4,
    expense: 3,
  },
  {
    id: "greek-chicken-bowls",
    title: "Greek Chicken Bowls",
    emoji: "🥙",
    rating: 3.9,
    servedCount: 2,
    showServedCount: false,
    plannedCostTier: 2,
    locked: false,
    isFavorite: false,
    recipeUrl: "https://weeklyeats.app/recipes/greek-chicken-bowls",
    ingredients: ["Chicken", "Tzatziki", "Pita"],
    difficulty: 2,
    expense: 2,
  },
  {
    id: "vegan-pad-thai",
    title: "Vegan Pad Thai",
    emoji: "🥦",
    rating: 4.0,
    servedCount: 4,
    showServedCount: true,
    plannedCostTier: 2,
    locked: false,
    isFavorite: true,
    recipeUrl: "https://weeklyeats.app/recipes/vegan-pad-thai",
    ingredients: ["Rice noodles", "Tofu", "Peanut sauce"],
    difficulty: 3,
    expense: 2,
  },
  {
    id: "slow-cooker-chili",
    title: "Slow Cooker Chili",
    emoji: "🌶️",
    rating: 3.4,
    servedCount: 6,
    showServedCount: false,
    plannedCostTier: 1,
    locked: false,
    isFavorite: false,
    recipeUrl: "https://weeklyeats.app/recipes/slow-cooker-chili",
    ingredients: ["Ground beef", "Beans", "Tomatoes"],
    difficulty: 1,
    expense: 1,
  },
  {
    id: "caprese-chicken",
    title: "Caprese Stuffed Chicken",
    emoji: "🍅",
    rating: 4.3,
    servedCount: 3,
    showServedCount: true,
    plannedCostTier: 2,
    locked: false,
    isFavorite: true,
    recipeUrl: "https://weeklyeats.app/recipes/caprese-chicken",
    ingredients: ["Chicken breast", "Mozzarella", "Basil"],
    difficulty: 3,
    expense: 3,
  },
];
