import { buildAutoPlan } from "../components/plan-week/autoPlan";
import { createEmptyDayPinsMap } from "../types/dayPins";
import { Meal } from "../types/meals";
import { createEmptyCurrentPlannedWeek } from "../types/weekPlan";

const meal = (id: string, values: Partial<Meal> = {}): Meal => ({
  id,
  title: id,
  emoji: "🍽️",
  rating: 0,
  servedCount: 0,
  showServedCount: false,
  plannedCostTier: 2,
  locked: false,
  isFavorite: false,
  ...values,
});

describe("buildAutoPlan", () => {
  it("fills only unplanned days without duplicate meals", () => {
    const plannedWeek = {
      ...createEmptyCurrentPlannedWeek(),
      mon: "existing",
    };
    const assignments = buildAutoPlan({
      days: ["mon", "tue", "wed"],
      meals: [
        meal("existing"),
        meal("favorite", { rating: 5, isFavorite: true }),
        meal("easy", { difficulty: 1 }),
      ],
      plannedWeek,
      dayPinsMap: createEmptyDayPinsMap(),
      servedEntries: [],
    });

    expect(assignments.map(({ day }) => day)).toEqual(["tue", "wed"]);
    expect(new Set(assignments.map(({ meal }) => meal.id)).size).toBe(2);
    expect(assignments.some(({ meal }) => meal.id === "existing")).toBe(false);
  });

  it("penalizes meals generated by the previous draft", () => {
    const assignments = buildAutoPlan({
      days: ["mon"],
      meals: [meal("first", { rating: 5 }), meal("alternate", { rating: 4 })],
      plannedWeek: createEmptyCurrentPlannedWeek(),
      dayPinsMap: createEmptyDayPinsMap(),
      servedEntries: [],
      previousGeneratedMealIds: new Set(["first"]),
    });

    expect(assignments[0]?.meal.id).toBe("alternate");
  });

  it("includes the first non-empty preferred side with an assignment", () => {
    const assignments = buildAutoPlan({
      days: ["mon"],
      meals: [
        meal("ramen", {
          preferredSides: ["  ", "Cucumber Salad", "Edamame"],
        }),
      ],
      plannedWeek: createEmptyCurrentPlannedWeek(),
      dayPinsMap: createEmptyDayPinsMap(),
      servedEntries: [],
    });

    expect(assignments[0]?.side).toBe("Cucumber Salad");
  });
});
